/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Existing brand scale (kept so primary-600 etc. keep working).
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        // Material 3 design tokens (from the Apex CRM design system).
        background: '#f6faff',
        'on-background': '#171c20',
        surface: '#f6faff',
        'surface-bright': '#f6faff',
        'surface-dim': '#d6dae0',
        'surface-variant': '#dee3e9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4fa',
        'surface-container': '#eaeef4',
        'surface-container-high': '#e4e8ee',
        'surface-container-highest': '#dee3e9',
        'on-surface': '#171c20',
        'on-surface-variant': '#3e4850',
        'inverse-surface': '#2c3135',
        'inverse-on-surface': '#edf1f7',
        outline: '#6e7881',
        'outline-variant': '#bec8d2',
        'primary-container': '#0ea5e9',
        'on-primary-container': '#003751',
        'on-primary': '#ffffff',
        'primary-fixed': '#c9e6ff',
        'primary-fixed-dim': '#89ceff',
        'on-primary-fixed-variant': '#004c6e',
        secondary: '#4648d4',
        'secondary-container': '#6063ee',
        'secondary-fixed': '#e1e0ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary: '#8a5100',
        'tertiary-container': '#de8712',
        'tertiary-fixed': '#ffdcbd',
        'on-tertiary-fixed-variant': '#693c00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
    },
  },
  plugins: [],
}
